/**
 * Auto-generated Documentation Manifest
 * 
 * This file is automatically generated by scanning the docs/ folder.
 * Do not edit manually - changes will be overwritten.
 * 
 * To regenerate: bun run generate:docs-manifest
 * Generated: 2026-03-31T03:41:43.454Z
 */

export const DOCS_MANIFEST = [
  {
    "id": "01-GETTING_STARTED",
    "fileId": "01-GETTING_STARTED",
    "label": "Getting Started with Production CRUD Integrations",
    "filename": "01-GETTING_STARTED.md",
    "path": "docs/01-GETTING_STARTED.md",
    "category": "Getting Started",
    "icon": "🚀",
    "order": 1,
    "description": ""
  },
  {
    "id": "02-sqlite-crud-production",
    "fileId": "02-sqlite-crud-production",
    "label": "Production-Ready SQLite CRUD Integration",
    "filename": "02-sqlite-crud-production.md",
    "path": "docs/02-sqlite-crud-production.md",
    "category": "Database Guides",
    "icon": "🗄️",
    "order": 2,
    "description": ""
  },
  {
    "id": "03-duckdb-crud-production",
    "fileId": "03-duckdb-crud-production",
    "label": "Production-Ready DuckDB CRUD Integration",
    "filename": "03-duckdb-crud-production.md",
    "path": "docs/03-duckdb-crud-production.md",
    "category": "Database Guides",
    "icon": "🗄️",
    "order": 2,
    "description": ""
  },
  {
    "id": "04-api-reference",
    "fileId": "04-api-reference",
    "label": "CRUD API Reference",
    "filename": "04-api-reference.md",
    "path": "docs/04-api-reference.md",
    "category": "API Reference",
    "icon": "📚",
    "order": 3,
    "description": ""
  },
  {
    "id": "05-security-best-practices",
    "fileId": "05-security-best-practices",
    "label": "Security Best Practices for CRUD Integrations",
    "filename": "05-security-best-practices.md",
    "path": "docs/05-security-best-practices.md",
    "category": "Security",
    "icon": "🔒",
    "order": 4,
    "description": ""
  },
  {
    "id": "SECURITY_AUDIT_FINDINGS",
    "fileId": "SECURITY_AUDIT_FINDINGS",
    "label": "Security Audit Findings Report",
    "filename": "SECURITY_AUDIT_FINDINGS.md",
    "path": "docs/SECURITY_AUDIT_FINDINGS.md",
    "category": "Security",
    "icon": "🛡️",
    "order": 4,
    "description": ""
  },
  {
    "id": "SECURITY_AUDIT_PLAN",
    "fileId": "SECURITY_AUDIT_PLAN",
    "label": "Security Audit & Testing Plan",
    "filename": "SECURITY_AUDIT_PLAN.md",
    "path": "docs/SECURITY_AUDIT_PLAN.md",
    "category": "Security",
    "icon": "🛡️",
    "order": 4,
    "description": ""
  },
  {
    "id": "SECURITY_AUDIT_SUMMARY",
    "fileId": "SECURITY_AUDIT_SUMMARY",
    "label": "Security Audit Summary & Remediation Report",
    "filename": "SECURITY_AUDIT_SUMMARY.md",
    "path": "docs/SECURITY_AUDIT_SUMMARY.md",
    "category": "Security",
    "icon": "🛡️",
    "order": 4,
    "description": ""
  },
  {
    "id": "SECURITY_REMEDIATION_COMPLETE",
    "fileId": "SECURITY_REMEDIATION_COMPLETE",
    "label": "Security Remediation Complete",
    "filename": "SECURITY_REMEDIATION_COMPLETE.md",
    "path": "docs/SECURITY_REMEDIATION_COMPLETE.md",
    "category": "Security",
    "icon": "🛡️",
    "order": 4,
    "description": ""
  },
  {
    "id": "06-deployment-production",
    "fileId": "06-deployment-production",
    "label": "Production Deployment Guide for CRUD Integrations",
    "filename": "06-deployment-production.md",
    "path": "docs/06-deployment-production.md",
    "category": "Deployment",
    "icon": "📦",
    "order": 5,
    "description": ""
  },
  {
    "id": "SECURE_DEPLOYMENT",
    "fileId": "SECURE_DEPLOYMENT",
    "label": "Secure Deployment Guide",
    "filename": "SECURE_DEPLOYMENT.md",
    "path": "docs/SECURE_DEPLOYMENT.md",
    "category": "Deployment",
    "icon": "🔐",
    "order": 5,
    "description": ""
  },
  {
    "id": "PROFESSIONAL_DEMOS",
    "fileId": "PROFESSIONAL_DEMOS",
    "label": "Professional Demo Components Refactoring",
    "filename": "PROFESSIONAL_DEMOS.md",
    "path": "docs/PROFESSIONAL_DEMOS.md",
    "category": "Professional Features",
    "icon": "🎨",
    "order": 6,
    "description": ""
  },
  {
    "id": "DATA_PERSISTENCE_GUIDE",
    "fileId": "DATA_PERSISTENCE_GUIDE",
    "label": "Data Persistence Guide",
    "filename": "DATA_PERSISTENCE_GUIDE.md",
    "path": "docs/DATA_PERSISTENCE_GUIDE.md",
    "category": "Data Management",
    "icon": "💾",
    "order": 7,
    "description": ""
  },
  {
    "id": "REFACTORING",
    "fileId": "REFACTORING",
    "label": "Refactoring Documentation",
    "filename": "REFACTORING.md",
    "path": "docs/REFACTORING.md",
    "category": "Refactoring",
    "icon": "♻️",
    "order": 8,
    "description": ""
  },
  {
    "id": "REFACTORING_PHASE1_COMPLETE",
    "fileId": "REFACTORING_PHASE1_COMPLETE",
    "label": "Refactoring Implementation Summary",
    "filename": "REFACTORING_PHASE1_COMPLETE.md",
    "path": "docs/REFACTORING_PHASE1_COMPLETE.md",
    "category": "Refactoring",
    "icon": "♻️",
    "order": 8,
    "description": ""
  },
  {
    "id": "ABSTRACTION_AUDIT",
    "fileId": "ABSTRACTION_AUDIT",
    "label": "Abstraction Audit Report",
    "filename": "ABSTRACTION_AUDIT.md",
    "path": "docs/ABSTRACTION_AUDIT.md",
    "category": "Architecture",
    "icon": "🏗️",
    "order": 9,
    "description": ""
  },
  {
    "id": "DEMO_IMPLEMENTATION",
    "fileId": "DEMO_IMPLEMENTATION",
    "label": "Production CRUD Demo Implementation Guide",
    "filename": "DEMO_IMPLEMENTATION.md",
    "path": "docs/DEMO_IMPLEMENTATION.md",
    "category": "New Features",
    "icon": "✨",
    "order": 10,
    "description": ""
  },
  {
    "id": "NEW_DEMO_COMPONENTS",
    "fileId": "NEW_DEMO_COMPONENTS",
    "label": "New Demo Components Implementation Summary",
    "filename": "NEW_DEMO_COMPONENTS.md",
    "path": "docs/NEW_DEMO_COMPONENTS.md",
    "category": "New Features",
    "icon": "✨",
    "order": 10,
    "description": ""
  },
  {
    "id": "BUILD_REPORT",
    "fileId": "BUILD_REPORT",
    "label": "Build and Compilation Report",
    "filename": "BUILD_REPORT.md",
    "path": "docs/BUILD_REPORT.md",
    "category": "Documentation",
    "icon": "📄",
    "order": 99,
    "description": ""
  },
  {
    "id": "DOCUMENTATION_MENU_FIX",
    "fileId": "DOCUMENTATION_MENU_FIX",
    "label": "Documentation Menu Rendering Fix",
    "filename": "DOCUMENTATION_MENU_FIX.md",
    "path": "docs/DOCUMENTATION_MENU_FIX.md",
    "category": "Documentation",
    "icon": "📄",
    "order": 99,
    "description": ""
  },
  {
    "id": "DYNAMIC_DOCS_MENU",
    "fileId": "DYNAMIC_DOCS_MENU",
    "label": "Dynamic Documentation Menu System",
    "filename": "DYNAMIC_DOCS_MENU.md",
    "path": "docs/DYNAMIC_DOCS_MENU.md",
    "category": "Documentation",
    "icon": "📄",
    "order": 99,
    "description": ""
  },
  {
    "id": "INDEX",
    "fileId": "INDEX",
    "label": "Production CRUD Documentation Index",
    "filename": "INDEX.md",
    "path": "docs/INDEX.md",
    "category": "Documentation",
    "icon": "📄",
    "order": 99,
    "description": ""
  },
  {
    "id": "VEGA_CHARTS_INTEGRATION",
    "fileId": "VEGA_CHARTS_INTEGRATION",
    "label": "Vega Charts Integration",
    "filename": "VEGA_CHARTS_INTEGRATION.md",
    "path": "docs/VEGA_CHARTS_INTEGRATION.md",
    "category": "Documentation",
    "icon": "📄",
    "order": 99,
    "description": ""
  }
];

export const DOCS_BY_CATEGORY = [
  {
    "label": "Getting Started",
    "icon": "🚀",
    "order": 1,
    "items": [
      {
        "id": "01-GETTING_STARTED",
        "fileId": "01-GETTING_STARTED",
        "label": "Getting Started with Production CRUD Integrations",
        "filename": "01-GETTING_STARTED.md",
        "path": "docs/01-GETTING_STARTED.md",
        "category": "Getting Started",
        "icon": "🚀",
        "order": 1,
        "description": ""
      }
    ]
  },
  {
    "label": "Database Guides",
    "icon": "🗄️",
    "order": 2,
    "items": [
      {
        "id": "02-sqlite-crud-production",
        "fileId": "02-sqlite-crud-production",
        "label": "Production-Ready SQLite CRUD Integration",
        "filename": "02-sqlite-crud-production.md",
        "path": "docs/02-sqlite-crud-production.md",
        "category": "Database Guides",
        "icon": "🗄️",
        "order": 2,
        "description": ""
      },
      {
        "id": "03-duckdb-crud-production",
        "fileId": "03-duckdb-crud-production",
        "label": "Production-Ready DuckDB CRUD Integration",
        "filename": "03-duckdb-crud-production.md",
        "path": "docs/03-duckdb-crud-production.md",
        "category": "Database Guides",
        "icon": "🗄️",
        "order": 2,
        "description": ""
      }
    ]
  },
  {
    "label": "API Reference",
    "icon": "📚",
    "order": 3,
    "items": [
      {
        "id": "04-api-reference",
        "fileId": "04-api-reference",
        "label": "CRUD API Reference",
        "filename": "04-api-reference.md",
        "path": "docs/04-api-reference.md",
        "category": "API Reference",
        "icon": "📚",
        "order": 3,
        "description": ""
      }
    ]
  },
  {
    "label": "Security",
    "icon": "🔒",
    "order": 4,
    "items": [
      {
        "id": "05-security-best-practices",
        "fileId": "05-security-best-practices",
        "label": "Security Best Practices for CRUD Integrations",
        "filename": "05-security-best-practices.md",
        "path": "docs/05-security-best-practices.md",
        "category": "Security",
        "icon": "🔒",
        "order": 4,
        "description": ""
      },
      {
        "id": "SECURITY_AUDIT_FINDINGS",
        "fileId": "SECURITY_AUDIT_FINDINGS",
        "label": "Security Audit Findings Report",
        "filename": "SECURITY_AUDIT_FINDINGS.md",
        "path": "docs/SECURITY_AUDIT_FINDINGS.md",
        "category": "Security",
        "icon": "🛡️",
        "order": 4,
        "description": ""
      },
      {
        "id": "SECURITY_AUDIT_PLAN",
        "fileId": "SECURITY_AUDIT_PLAN",
        "label": "Security Audit & Testing Plan",
        "filename": "SECURITY_AUDIT_PLAN.md",
        "path": "docs/SECURITY_AUDIT_PLAN.md",
        "category": "Security",
        "icon": "🛡️",
        "order": 4,
        "description": ""
      },
      {
        "id": "SECURITY_AUDIT_SUMMARY",
        "fileId": "SECURITY_AUDIT_SUMMARY",
        "label": "Security Audit Summary & Remediation Report",
        "filename": "SECURITY_AUDIT_SUMMARY.md",
        "path": "docs/SECURITY_AUDIT_SUMMARY.md",
        "category": "Security",
        "icon": "🛡️",
        "order": 4,
        "description": ""
      },
      {
        "id": "SECURITY_REMEDIATION_COMPLETE",
        "fileId": "SECURITY_REMEDIATION_COMPLETE",
        "label": "Security Remediation Complete",
        "filename": "SECURITY_REMEDIATION_COMPLETE.md",
        "path": "docs/SECURITY_REMEDIATION_COMPLETE.md",
        "category": "Security",
        "icon": "🛡️",
        "order": 4,
        "description": ""
      }
    ]
  },
  {
    "label": "Deployment",
    "icon": "📦",
    "order": 5,
    "items": [
      {
        "id": "06-deployment-production",
        "fileId": "06-deployment-production",
        "label": "Production Deployment Guide for CRUD Integrations",
        "filename": "06-deployment-production.md",
        "path": "docs/06-deployment-production.md",
        "category": "Deployment",
        "icon": "📦",
        "order": 5,
        "description": ""
      },
      {
        "id": "SECURE_DEPLOYMENT",
        "fileId": "SECURE_DEPLOYMENT",
        "label": "Secure Deployment Guide",
        "filename": "SECURE_DEPLOYMENT.md",
        "path": "docs/SECURE_DEPLOYMENT.md",
        "category": "Deployment",
        "icon": "🔐",
        "order": 5,
        "description": ""
      }
    ]
  },
  {
    "label": "Professional Features",
    "icon": "🎨",
    "order": 6,
    "items": [
      {
        "id": "PROFESSIONAL_DEMOS",
        "fileId": "PROFESSIONAL_DEMOS",
        "label": "Professional Demo Components Refactoring",
        "filename": "PROFESSIONAL_DEMOS.md",
        "path": "docs/PROFESSIONAL_DEMOS.md",
        "category": "Professional Features",
        "icon": "🎨",
        "order": 6,
        "description": ""
      }
    ]
  },
  {
    "label": "Data Management",
    "icon": "💾",
    "order": 7,
    "items": [
      {
        "id": "DATA_PERSISTENCE_GUIDE",
        "fileId": "DATA_PERSISTENCE_GUIDE",
        "label": "Data Persistence Guide",
        "filename": "DATA_PERSISTENCE_GUIDE.md",
        "path": "docs/DATA_PERSISTENCE_GUIDE.md",
        "category": "Data Management",
        "icon": "💾",
        "order": 7,
        "description": ""
      }
    ]
  },
  {
    "label": "Refactoring",
    "icon": "♻️",
    "order": 8,
    "items": [
      {
        "id": "REFACTORING",
        "fileId": "REFACTORING",
        "label": "Refactoring Documentation",
        "filename": "REFACTORING.md",
        "path": "docs/REFACTORING.md",
        "category": "Refactoring",
        "icon": "♻️",
        "order": 8,
        "description": ""
      },
      {
        "id": "REFACTORING_PHASE1_COMPLETE",
        "fileId": "REFACTORING_PHASE1_COMPLETE",
        "label": "Refactoring Implementation Summary",
        "filename": "REFACTORING_PHASE1_COMPLETE.md",
        "path": "docs/REFACTORING_PHASE1_COMPLETE.md",
        "category": "Refactoring",
        "icon": "♻️",
        "order": 8,
        "description": ""
      }
    ]
  },
  {
    "label": "Architecture",
    "icon": "🏗️",
    "order": 9,
    "items": [
      {
        "id": "ABSTRACTION_AUDIT",
        "fileId": "ABSTRACTION_AUDIT",
        "label": "Abstraction Audit Report",
        "filename": "ABSTRACTION_AUDIT.md",
        "path": "docs/ABSTRACTION_AUDIT.md",
        "category": "Architecture",
        "icon": "🏗️",
        "order": 9,
        "description": ""
      }
    ]
  },
  {
    "label": "New Features",
    "icon": "✨",
    "order": 10,
    "items": [
      {
        "id": "DEMO_IMPLEMENTATION",
        "fileId": "DEMO_IMPLEMENTATION",
        "label": "Production CRUD Demo Implementation Guide",
        "filename": "DEMO_IMPLEMENTATION.md",
        "path": "docs/DEMO_IMPLEMENTATION.md",
        "category": "New Features",
        "icon": "✨",
        "order": 10,
        "description": ""
      },
      {
        "id": "NEW_DEMO_COMPONENTS",
        "fileId": "NEW_DEMO_COMPONENTS",
        "label": "New Demo Components Implementation Summary",
        "filename": "NEW_DEMO_COMPONENTS.md",
        "path": "docs/NEW_DEMO_COMPONENTS.md",
        "category": "New Features",
        "icon": "✨",
        "order": 10,
        "description": ""
      }
    ]
  },
  {
    "label": "Documentation",
    "icon": "📄",
    "order": 99,
    "items": [
      {
        "id": "BUILD_REPORT",
        "fileId": "BUILD_REPORT",
        "label": "Build and Compilation Report",
        "filename": "BUILD_REPORT.md",
        "path": "docs/BUILD_REPORT.md",
        "category": "Documentation",
        "icon": "📄",
        "order": 99,
        "description": ""
      },
      {
        "id": "DOCUMENTATION_MENU_FIX",
        "fileId": "DOCUMENTATION_MENU_FIX",
        "label": "Documentation Menu Rendering Fix",
        "filename": "DOCUMENTATION_MENU_FIX.md",
        "path": "docs/DOCUMENTATION_MENU_FIX.md",
        "category": "Documentation",
        "icon": "📄",
        "order": 99,
        "description": ""
      },
      {
        "id": "DYNAMIC_DOCS_MENU",
        "fileId": "DYNAMIC_DOCS_MENU",
        "label": "Dynamic Documentation Menu System",
        "filename": "DYNAMIC_DOCS_MENU.md",
        "path": "docs/DYNAMIC_DOCS_MENU.md",
        "category": "Documentation",
        "icon": "📄",
        "order": 99,
        "description": ""
      },
      {
        "id": "INDEX",
        "fileId": "INDEX",
        "label": "Production CRUD Documentation Index",
        "filename": "INDEX.md",
        "path": "docs/INDEX.md",
        "category": "Documentation",
        "icon": "📄",
        "order": 99,
        "description": ""
      },
      {
        "id": "VEGA_CHARTS_INTEGRATION",
        "fileId": "VEGA_CHARTS_INTEGRATION",
        "label": "Vega Charts Integration",
        "filename": "VEGA_CHARTS_INTEGRATION.md",
        "path": "docs/VEGA_CHARTS_INTEGRATION.md",
        "category": "Documentation",
        "icon": "📄",
        "order": 99,
        "description": ""
      }
    ]
  }
];

export const DOCS_MAP = Object.fromEntries(
  DOCS_MANIFEST.map(doc => [doc.id, doc])
);

export const DOCS_COUNT = DOCS_MANIFEST.length;
